# These are supported funding model platforms
# Uncomment and add your usernames to enable funding links

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# polar: username
# buy_me_a_coffee: username
# thanks_dev: username
# custom: ['https://example.com']
